# -*- coding: utf-8 -*-
"""Speaker_Identification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ux_KPo5gOQi_8emILQ5OzDPy_j6trGAQ
"""

import torch

import numpy as np
import librosa
import pickle as pickle
from scipy.io.wavfile import read
import os
import random
import matplotlib.pyplot as plt
import librosa.display

from google.colab import files
uploaded=files.upload()

signal, rate = librosa.load('Rohit_1.wav', sr=44100)
spec = librosa.feature.melspectrogram(signal, sr=44100, hop_length=441)
plt.subplot(2,1,1)
librosa.display.specshow(librosa.power_to_db(np.abs(librosa.stft(signal)), ref=np.max), y_axis='mel', x_axis='time')
plt.title('Mel Spectrogram ')
plt.show()

x = librosa.feature.mfcc(signal, sr=44100, n_mfcc=20)

x.shape
l = []
y = x[:, :400]
l.append(y)
l

from google.colab import files
uploaded=files.upload()

signal, rate = librosa.load('Rohit_2.wav', sr=44100)
spec = librosa.feature.melspectrogram(signal, sr=44100, hop_length=441)
plt.subplot(2,1,1)
librosa.display.specshow(librosa.power_to_db(np.abs(librosa.stft(signal)), ref=np.max), y_axis='mel', x_axis='time')
plt.title('Mel Spectrogram ')
plt.show()

x = librosa.feature.mfcc(signal, sr=44100, n_mfcc=20)

x.shape
x

y = x[:,:400]
l.append(y)
l

from torch import nn

from google.colab import files
uploaded=files.upload()

signal, rate = librosa.load('Varun_1.wav', sr=44100)
spec = librosa.feature.melspectrogram(signal, sr=44100, hop_length=441)
plt.subplot(2,1,1)
librosa.display.specshow(librosa.power_to_db(np.abs(librosa.stft(signal)), ref=np.max), y_axis='mel', x_axis='time')
plt.title('Mel Spectrogram ')
plt.show()

x = librosa.feature.mfcc(signal, sr=44100, n_mfcc=20)
y = x[:,:400]
l.append(y)
l

signal, rate = librosa.load('Varun_2.wav', sr=44100)
spec = librosa.feature.melspectrogram(signal, sr=44100, hop_length=441)
plt.subplot(2,1,1)
librosa.display.specshow(librosa.power_to_db(np.abs(librosa.stft(signal)), ref=np.max), y_axis='mel', x_axis='time')
plt.title('Mel Spectrogram ')
plt.show()

x = librosa.feature.mfcc(signal, sr=44100, n_mfcc=20)
y = x[:,:400]
l.append(y)
l



